### ISSUE TITLE
Disparition du paiement en  3X conditioné au OneClick

### ISSUE THREAD

**Issue by SimonPallam** [easytransac/EasyTransac-Drupal-Commerce#3]
Je crois que le "return $form" à la ligne 238 devrait être en dehors de la boucle. Pouvez vous vérifier et éventuellement corriger cela?

Merci

`
function easytransac_submit_form($payment_method, $pane_values, $checkout_pane, $order)
{

    $form = array();

    if ($payment_method['settings']['multiple_payments'] && easytransac__order_supports_multiple_payments($order)) {

        // Order amount.
        $amount = easytransac__order_amount($order);
        $down_payments = easytransac__down_payment($amount, TRUE);

        // Adds multiple payments opt in.
        $form['multiple_payments'] = array(
            '#type' => 'checkbox',
            '#title' => t('Paiement en 3 fois'),
        );
        $form['multiple_payments_rates'] = array(
            '#type' => 'container',
            '#attributes' => array(
                'class' => array(
                    'easytransac-multiple-payments-rates',
                ),
            ),
        );
        $form['multiple_payments_rates']['info'] = array(
            '#markup' => t("Paiement d'un premier acompte de @first suivi de deux mensualités de @second.", $down_payments),
        );
    }

    if (!empty($payment_method['settings']['one_click'])) {
        // Adds OneClick.
        $form['oneclick_namespace'] = array(
            '#type' => 'item',
            '#markup' => '<div id="easytransac-namespace"></div>',
        );
        $form['easytransac_is_oneclick'] = array(
            '#type' => 'hidden',
            '#default_value' => 'no',
            '#attributes' => array(
                'id' => 'easytransac_is_oneclick',
            )
        );
        $form['easytransac_oneclick_card'] = array(
            '#type' => 'hidden',
            '#default_value' => '',
            '#attributes' => array(
                'id' => 'easytransac_oneclick_card',
            )
        );
        $form['oneclick_namespace']['#attached']['js'] = array(
            drupal_get_path('module', 'easytransac') . '/js/oneclick.js',
        );
        return $form;
    }
}`

**Comment by maxime-killinger** [comment]
Fix
